WIP

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -177,40 +177,44 @@ install_halcyon () {
 			echo '   *** ERROR: Failed to create base directory' >&2
 			return 1
 		fi
+	else
+		echo "-----> Using existing base directory: ${halcyon_base}" >&2
+	fi
 
-		local halcyon_dir
-		halcyon_dir="${HALCYON_DIR:-${halcyon_base}/halcyon}"
-		if [[ ! -d "${halcyon_dir}" ]]; then
-			local url base_url branch
-			url="${HALCYON_URL:-https://github.com/mietek/halcyon}"
-			base_url="${url%#*}"
-			branch="${url#*#}"
-			if [[ "${branch}" == "${base_url}" ]]; then
-				branch='master'
-			fi
-
-			echo "-----> Creating Halcyon directory: ${halcyon_dir}" >&2
-
-			if ! mkdir -p "${halcyon_dir}" 2>'/dev/null'; then
-				echo '   *** ERROR: Failed to create Halcyon directory' >&2
-				return 1
-			fi
-
-			printf -- '-----> Cloning Halcyon repository...' >&2
-
-			local commit_hash
-			if ! commit_hash=$(
-				git clone -q "${base_url}" "${halcyon_dir}" >'/dev/null' 2>&1 &&
-				cd "${halcyon_dir}" &&
-				git checkout -q "${branch}" >'/dev/null' 2>&1 &&
-				git log -n 1 --pretty='format:%h'
-			); then
-				echo ' error' >&2
-				echo '   *** ERROR: Failed to clone Halcyon repository' >&2
-				return 1
-			fi
-			echo " done, ${commit_hash}" >&2
+	local halcyon_dir
+	halcyon_dir="${HALCYON_DIR:-${halcyon_base}/halcyon}"
+	if [[ ! -d "${halcyon_dir}" ]]; then
+		local url base_url branch
+		url="${HALCYON_URL:-https://github.com/mietek/halcyon}"
+		base_url="${url%#*}"
+		branch="${url#*#}"
+		if [[ "${branch}" == "${base_url}" ]]; then
+			branch='master'
 		fi
+
+		echo "-----> Creating Halcyon directory: ${halcyon_dir}" >&2
+
+		if ! mkdir -p "${halcyon_dir}" 2>'/dev/null'; then
+			echo '   *** ERROR: Failed to create Halcyon directory' >&2
+			return 1
+		fi
+
+		printf -- '-----> Cloning Halcyon repository...' >&2
+
+		local commit_hash
+		if ! commit_hash=$(
+			git clone -q "${base_url}" "${halcyon_dir}" >'/dev/null' 2>&1 &&
+			cd "${halcyon_dir}" &&
+			git checkout -q "${branch}" >'/dev/null' 2>&1 &&
+			git log -n 1 --pretty='format:%h'
+		); then
+			echo ' error' >&2
+			echo '   *** ERROR: Failed to clone Halcyon repository' >&2
+			return 1
+		fi
+		echo " done, ${commit_hash}" >&2
+	else
+		echo "-----> Using existing Halcyon directory: ${halcyon_dir}" >&2
 	fi
 
 	echo >&2
